### PR TITLE
fix: avoid revoke token when appSecret is empty

### PR DESCRIPTION
**Pull request by embbnux**
Not sure if i need to submit build files

### CODE REVIEW

**Comment by embbnux** [comment]
for #117

**Comment by kirill-konshin** [comment]
> Not sure if i need to submit build files
Which ones?

**Comment by embbnux** [comment]
@kirill-konshin files in v3 branch build folder

**Comment by kirill-konshin** [comment]
V3 has integration with Bower, which is discontinued. As well as V3 branch itself ))) you should do the PR for V4. For V3 you have to push build too.

**Comment by embbnux** [comment]
Create a new PR for build files for V3 #121 . In V4, we have done this to check secret before request

**Pull request merged**
